/* ============================================
   VibeGallery — Shared Gallery Data (24 Items)
   ============================================ */

const galleryData = [
    {
        id: 1,
        title: "Analytics Dashboard",
        subtitle: "Dashboard Design",
        description: "A modern, sleek dark-themed dashboard with analytics charts, sidebar navigation, and gradient purple-blue accents. Built for real-time data visualization.",
        image: "assets/images/dashboard_design.jpg",
        category: "dashboard",
        language: "en",
        tags: ["Dark UI", "Charts", "Analytics"],
        link: "#",
        stats: { views: "1.2k", likes: "489", shares: "87" },
        emoji: "📊"
    },
    {
        id: 2,
        title: "متجر شوب فايب",
        subtitle: "Arabic E-Commerce Platform",
        description: "Full RTL Arabic e-commerce experience with elegant product cards, shopping cart UI, and rich warm coral palette — built for Arabic-speaking markets.",
        image: "assets/images/ecommerce_design.jpg",
        category: "ecommerce",
        language: "ar",
        tags: ["Arabic RTL", "Shopping", "Warm Palette"],
        link: "#",
        stats: { views: "2.4k", likes: "812", shares: "156" },
        emoji: "🛍️"
    },
    {
        id: 3,
        title: "创意工作室",
        subtitle: "Chinese Creative Studio",
        description: "Bold Chinese creative agency portfolio with Hanzi typography, dark mode layout, and striking neon accents — designed for the Chinese design market.",
        image: "assets/images/portfolio_design.jpg",
        category: "landing",
        language: "zh",
        tags: ["Chinese", "Portfolio", "Neon"],
        link: "#",
        stats: { views: "987", likes: "345", shares: "64" },
        emoji: "🎨"
    },
    {
        id: 4,
        title: "CloudSync SaaS Landing",
        subtitle: "Landing Page",
        description: "Stunning SaaS landing page with a bold hero section, floating 3D elements, gradient mesh background, and call-to-action buttons. Designed for modern startups.",
        image: "assets/images/landing_design.jpg",
        category: "landing",
        language: "en",
        tags: ["SaaS", "3D Elements", "Gradient Mesh"],
        link: "#",
        stats: { views: "3.1k", likes: "1.1k", shares: "234" },
        emoji: "☁️"
    },
    {
        id: 5,
        title: "コネクトハブ",
        subtitle: "Japanese Social Platform",
        description: "Japanese social media platform with clean feed layout, user profile cards, stories bar, and messaging sidebar — crafted with Japanese UI sensibility.",
        image: "assets/images/social_design.jpg",
        category: "app",
        language: "ja",
        tags: ["Japanese", "Social Media", "Feed"],
        link: "#",
        stats: { views: "1.8k", likes: "623", shares: "112" },
        emoji: "💬"
    },
    {
        id: 6,
        title: "SoundWave Music App",
        subtitle: "Music Streaming",
        description: "Dark-themed music streaming app with album art grid, now-playing bar, sidebar playlist, and waveform visualizer. Deep purple and magenta gradient design.",
        image: "assets/images/music_design.jpg",
        category: "app",
        language: "en",
        tags: ["Music", "Streaming", "Dark Mode"],
        link: "#",
        stats: { views: "2.1k", likes: "756", shares: "143" },
        emoji: "🎵"
    },
    {
        id: 7,
        title: "لوحة تحكم المالية",
        subtitle: "Arabic Fintech Dashboard",
        description: "RTL Arabic fintech admin platform with custom chart modules, expense trackers, and quick transaction panels — designed for Arabic-speaking financial users.",
        image: "assets/images/dashboard_design.jpg",
        category: "dashboard",
        language: "ar",
        tags: ["Arabic RTL", "Fintech", "Finance"],
        link: "#",
        stats: { views: "3.2k", likes: "1.1k", shares: "189" },
        emoji: "💳"
    },
    {
        id: 8,
        title: "バイブポートフォリオ",
        subtitle: "Japanese Minimalist Portfolio",
        description: "Sleek Japanese personal portfolio using Wa-inspired minimalism, organic spacing, and clean typographic hierarchy — a serene visual art showcase.",
        image: "assets/images/portfolio_design.jpg",
        category: "landing",
        language: "ja",
        tags: ["Japanese", "Minimal", "Portfolio"],
        link: "#",
        stats: { views: "4.5k", likes: "1.8k", shares: "312" },
        emoji: "👤"
    },
    {
        id: 9,
        title: "Apex Crypto Exchange",
        subtitle: "Cryptocurrency Platform",
        description: "An interactive crypto asset dashboard featuring live price feeds, market trends, dark mode aesthetic, and custom trading modules.",
        image: "assets/images/dashboard_design.jpg",
        category: "dashboard",
        language: "en",
        tags: ["Crypto", "Exchange", "Dark Mode"],
        link: "#",
        stats: { views: "5.4k", likes: "2.2k", shares: "411" },
        emoji: "🪙"
    },
    {
        id: 10,
        title: "منصة التداول السريع",
        subtitle: "Arabic Trading Hub",
        description: "Arabic financial trading platform utilizing custom charting APIs, transaction summaries, and real-time news alerts in a cozy layout.",
        image: "assets/images/dashboard_design.jpg",
        category: "dashboard",
        language: "ar",
        tags: ["Arabic RTL", "Trading", "Charts"],
        link: "#",
        stats: { views: "1.9k", likes: "721", shares: "92" },
        emoji: "📈"
    },
    {
        id: 11,
        title: "Zenith SaaS Platform",
        subtitle: "SaaS Dashboard",
        description: "High-end product management dashboard with tasks kanban, team workspaces, activity trackers, and soft emerald green highlight themes.",
        image: "assets/images/dashboard_design.jpg",
        category: "dashboard",
        language: "en",
        tags: ["SaaS", "Kanban", "Management"],
        link: "#",
        stats: { views: "2.8k", likes: "980", shares: "124" },
        emoji: "🛠️"
    },
    {
        id: 12,
        title: "ShopVibe Boutique",
        subtitle: "Modern E-Commerce Store",
        description: "Clean minimalist fashion e-commerce storefront with organic grid layouts, interactive product zooms, and dynamic shopping carts.",
        image: "assets/images/ecommerce_design.jpg",
        category: "ecommerce",
        language: "en",
        tags: ["Shopping", "Minimalist", "Fashion"],
        link: "#",
        stats: { views: "3.7k", likes: "1.4k", shares: "298" },
        emoji: "🏷️"
    },
    {
        id: 13,
        title: "شراء وتوصيل",
        subtitle: "Arabic Grocery App",
        description: "Arabic local delivery marketplace interface showing food grids, quick filters, cart totals, and RTL maps navigation modules.",
        image: "assets/images/ecommerce_design.jpg",
        category: "ecommerce",
        language: "ar",
        tags: ["Arabic RTL", "Delivery", "Marketplace"],
        link: "#",
        stats: { views: "1.5k", likes: "512", shares: "67" },
        emoji: "🍎"
    },
    {
        id: 14,
        title: "ワンダーショップ",
        subtitle: "Japanese Visual Storefront",
        description: "Modern Japanese online bookstore interface designed with clean grids, paper texture backgrounds, and Japanese type layouts.",
        image: "assets/images/ecommerce_design.jpg",
        category: "ecommerce",
        language: "ja",
        tags: ["Japanese", "Books", "E-Commerce"],
        link: "#",
        stats: { views: "2.3k", likes: "899", shares: "143" },
        emoji: "📖"
    },
    {
        id: 15,
        title: "Nova Portfolio Landing",
        subtitle: "Creative Agency Showcase",
        description: "A dark creative agency landing page displaying high-quality grid cases, cursor-following animations, and bold typographic sliders.",
        image: "assets/images/portfolio_design.jpg",
        category: "landing",
        language: "en",
        tags: ["Agency", "Animations", "Case Studies"],
        link: "#",
        stats: { views: "4.1k", likes: "1.6k", shares: "310" },
        emoji: "🏢"
    },
    {
        id: 16,
        title: "صفحة الهبوط الرئيسية",
        subtitle: "Arabic Agency Landing",
        description: "RTL Arabic marketing landing page with custom hero layouts, service summaries, and high-converting contact forms in warm sand tones.",
        image: "assets/images/landing_design.jpg",
        category: "landing",
        language: "ar",
        tags: ["Arabic RTL", "Marketing", "Agency"],
        link: "#",
        stats: { views: "2.2k", likes: "840", shares: "109" },
        emoji: "🎯"
    },
    {
        id: 17,
        title: "デジタルエージェンシー",
        subtitle: "Japanese Agency Site",
        description: "Minimal Japanese interactive agency landing page showcasing modern typography, horizontal text scrolling, and subtle grid dividers.",
        image: "assets/images/landing_design.jpg",
        category: "landing",
        language: "ja",
        tags: ["Japanese", "Interactive", "Agency"],
        link: "#",
        stats: { views: "3.5k", likes: "1.3k", shares: "211" },
        emoji: "💫"
    },
    {
        id: 18,
        title: "设计新势力",
        subtitle: "Chinese Design Agency",
        description: "High-contrast Chinese design group showcase featuring bold editorial grids, vertical text columns, and stunning red accents.",
        image: "assets/images/portfolio_design.jpg",
        category: "landing",
        language: "zh",
        tags: ["Chinese", "Red Accents", "Grids"],
        link: "#",
        stats: { views: "1.7k", likes: "690", shares: "88" },
        emoji: "🔴"
    },
    {
        id: 19,
        title: "Pulse Social Messenger",
        subtitle: "Messaging Workspace",
        description: "A dark web app dashboard layout containing active user chat rooms, dynamic chat streams, media attachments, and custom status flags.",
        image: "assets/images/social_design.jpg",
        category: "app",
        language: "en",
        tags: ["Social", "Messenger", "App"],
        link: "#",
        stats: { views: "3.3k", likes: "1.2k", shares: "190" },
        emoji: "⚡"
    },
    {
        id: 20,
        title: "تطبيق التواصل المباشر",
        subtitle: "Arabic Chat Hub",
        description: "Arabic communication web app supporting active conversation lists, RTL message layouts, audio records, and interactive emoji selectors.",
        image: "assets/images/social_design.jpg",
        category: "app",
        language: "ar",
        tags: ["Arabic RTL", "Chat", "App"],
        link: "#",
        stats: { views: "2.0k", likes: "765", shares: "119" },
        emoji: "🗣️"
    },
    {
        id: 21,
        title: "ソーシャルスペース",
        subtitle: "Japanese Community Hub",
        description: "Japanese web portal for interactive group forums, story highlights, user profiles, and minimalist dark mode chat windows.",
        image: "assets/images/social_design.jpg",
        category: "app",
        language: "ja",
        tags: ["Japanese", "Forums", "App"],
        link: "#",
        stats: { views: "2.5k", likes: "987", shares: "134" },
        emoji: "👥"
    },
    {
        id: 22,
        title: "BeatCraft Beatmaker",
        subtitle: "Music Synthesizer",
        description: "An interactive music creation dashboard showing a step-sequencer, keyboard keys, loop selector pads, and live output meters.",
        image: "assets/images/music_design.jpg",
        category: "app",
        language: "en",
        tags: ["Music", "Synthesizer", "Sequencer"],
        link: "#",
        stats: { views: "4.8k", likes: "1.9k", shares: "389" },
        emoji: "🎹"
    },
    {
        id: 23,
        title: "تطبيق إنتاج الموسيقى",
        subtitle: "Arabic Synthesizer Platform",
        description: "Full Arabic audio workstation dashboard featuring synthesizer controls, timeline sequencers, volume sliders, and RTL layouts.",
        image: "assets/images/music_design.jpg",
        category: "app",
        language: "ar",
        tags: ["Arabic RTL", "Music", "Audio Workstation"],
        link: "#",
        stats: { views: "1.4k", likes: "512", shares: "76" },
        emoji: "🎙️"
    },
    {
        id: 24,
        title: "ビートクラフト",
        subtitle: "Japanese Audio Workspace",
        description: "Japanese sound production web application interface containing waveform sliders, beat templates, and minimal dark canvas charts.",
        image: "assets/images/music_design.jpg",
        category: "app",
        language: "ja",
        tags: ["Japanese", "Audio", "Workspace"],
        link: "#",
        stats: { views: "2.9k", likes: "1.1k", shares: "167" },
        emoji: "🎛️"
    }
];
